name: Enforce Branch Naming Convention

on:
  push:
    branches:
      - '**'  # Trigger for all branche

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce feature/** naming convention
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ ! "$BRANCH_NAME" =~ ^feature/.*$ ]]; then
            echo "Error: Branch name must follow 'feature/**' pattern."
            exit 1
          fi
